/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DrawerHeaderSection: typeof import('./src/components/DrawerHeaderSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MoreBtn: typeof import('./src/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitButton: typeof import('./src/components/SubmitButton.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
  }
}
